version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: >
      bash -c "alembic upgrade head &&
               uvicorn main:app --host 0.0.0.0 --port 8000"

  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - web
    command: pytest

  coverage:
    build: .
    volumes:
      - .:/app
    depends_on:
      - web
    command: >
      bash -c "pytest --cov=. --cov-report=html"